[build]
builder = "nixpacks"
buildCommand = "cd move-dashboard && npm install && npm run build"
watchPatterns = ["move-dashboard/**"]

[deploy]
startCommand = "cd move-dashboard && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
pkgs = ["nodejs_20"]
